workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Runner.ipa Payload/
          
    artifacts:
      - build/ios/iphoneos/*.ipa
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true